version: '3'
services:
  mariadb:
    image: mariadb:10.4
    ports: 
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: testdb
      MYSQL_USER: student
      MYSQL_PASSWORD: student
    restart: always
    volumes:
      - ./src/main/resources/scripts/mariadb.sql:/docker-entrypoint-initdb.d/init.sql
      - ./src/main/resources/scripts/create.sql:/docker-entrypoint-initdb.d/create.sql
      - ${PWD}/mariadb:/var/lib/mysql
  postgres:
    image: postgres:11.3
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: student
      POSTGRES_USER: student
    restart: always
    volumes:
      - ./src/main/resources/scripts/postgres.sql:/docker-entrypoint-initdb.d/init.sql
      - ${PWD}/postgres/data:/var/lib/postgresql/data:rw
  oracle:
    image: store/oracle/database-enterprise:12.2.0.1-slim
    ports:
      - "1521:1521"
      - "5500:5500"
    restart: always
    volumes:
      - ./src/main/resources/scripts/oracle:/opt/oracle/scripts/setup
      - ${PWD}/oracle/oradata:/opt/oracle/oradata